### ISSUE TITLE
Consider `import { cache } from 'react'` to eliminate Next internals dependency

### ISSUE THREAD

**Issue by gnoff** [apollographql/apollo-client-nextjs#10]
The `registerApolloClient` uses next internals to create a map of Request to apollo client. The idiomatic way would be to use the cache function exported in the version of React Next.js vendors.

https://github.com/apollographql/apollo-client-nextjs/blob/8bdc0cf5746a50987732980920f4067aa8d71c5c/package/src/rsc/registerApolloClient.tsx#L11C5-L24

you can see some documentation here: [Beta Next.js Docs: Cache](https://beta.nextjs.org/docs/data-fetching/caching#graphql-and-cache)

If you cache your function you can call it as many times as you want per Request and you'll always get the same result back (assuming you don't vary the args)

**Comment by phryneas** [comment]
For future reference: at this point, `React.cache` is only implemented in React Server Components: https://twitter.com/dan_abramov/status/1655212740632297473
