### ISSUE TITLE
Unable to attach Auth0 access token to headers inside Apollo client

### ISSUE THREAD

**Issue by yhbk12** [apollographql/apollo-client-nextjs#100]
Details shown here. Would love to get some help here, been struggling with this for a while now.

https://stackoverflow.com/questions/77164538/attach-auth0-access-token-as-request-header-for-graphql-apolloclient-in-nextjs-a

**Comment by mvandergrift** [comment]
I'm using Auth0 and nextjs to authenticate with apollo-client-nexts. I can give you the steps I'm using, but can't guarantee they'll make sense for you.

The Auth0 code you're using is designed to run on the server. Even if you could await it, that wouldn't work.

```js
// const accessToken = await getAccessToken();
    // const session = await getSession();
    // console.log('session', session);
````
Instead, what I did was to grab the access token in the root and pass that down through the props to the ApolloProvider.

````js
import { getAccessToken } from "@auth0/nextjs-auth0";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const token = await getAccessToken(); 

    return (
        <html lang="en">
            <body>
                <UserProvider>
                    <ApolloWrapper token={token} >
                            {children}                         
                    </ApolloWrapper>
                </UserProvider>
            </body>
        </html>
    );
}
````
````js


````

**Comment by yhbk12** [comment]
Thanks for the response @mvandergrift. Unfortunately whenever I try to make my `_app.js`, or `layout.js` functions async, I get this error:

"Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead."

Any idea why this happens? Seems like I'm unable to make anything async.

![image](https://github.com/apollographql/apollo-client-nextjs/assets/16723379/c5296a04-f6df-43f4-8a6f-0a211a57e488)

**Comment by mvandergrift** [comment]
It looks like you've built your project in the /pages directory instead of the /app directory, so you're not using the AppRouter. Async components are only available within the AppRouter framework. Hopefully, it's as easy as moving some files over and renaming a couple of pages. Otherwise, Vercel has a great guide on migration to the app router: https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.

**Comment by tomoima525** [comment]
FYI: As far as I read from Auth0 community discussion, `getAccessToken()` refreshes the access token internally hence you don't need to handle the refresh logic https://community.auth0.com/t/how-to-use-the-refresh-token-with-auth0-nextjs-auth0/126612
