### ISSUE TITLE
What would be right way to set a revalidation-tag on a specific query?

### ISSUE THREAD

**Issue by trm217** [apollographql/apollo-client-nextjs#120]
What would be the correct way to use this new apollo client in combination with tag revalidation?

The [next.js docs](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#on-demand-revalidation) say this is how to use it with 'fetch':
```js
export default async function Page() {
  const res = await fetch('https://...', { next: { tags: ['collection'] } })
  const data = await res.json()
  // ...
}```

So I assume it would work something like this with the apollo client?

```js
await client.query(MY_QUERY, { context: { next: { tags: ['MY_TAG'] } } })
```

Is that correct? I am unsure if I understood the docs correctly, as [context is just typed](https://www.apollographql.com/docs/react/data/queries/#context) as `Record<string, any>`.

**Comment by phryneas** [comment]
Almost!

It would be 
```js
await client.query(MY_QUERY, { context: { fetchOptions: { next: { tags: ['MY_TAG'] } } } })
```
