### ISSUE TITLE
Multiple Apollo instances implementation

### ISSUE THREAD

**Issue by coferrari** [apollographql/apollo-client-nextjs#121]
Hi, can multiple Apollo instances be created to connect them to different APIs? If so, can you please provide an example of the implementation? Thanks in advance

**Comment by phryneas** [comment]
For RSC, you could call `registerApolloClient` multiple times.

In Client Components, this is currently not possible. 
Generally, in most cases where you have to access multiple APIs, you would use the same Apollo Client instance and decide in the link chain, which API should be queried for it - assuming both APIs do not have overlap in types.
