### ISSUE TITLE
Authentication: How would I getClient with Clerk?

### ISSUE THREAD

**Issue by peterkuykendall** [apollographql/apollo-client-nextjs#123]
I'm only interested in the next js app folder approach at this point.

With Clerk for next.js app, I can get a token from a page, but I can't see how to get it from the environment like you do with the Next Auth approach https://github.com/apollographql/apollo-client-nextjs/issues/44

So I'd think I'd need to pass the token in with the getClient/registerApolloClient call in the examples, 
export const { getClient } = registerApolloClient(() => {

but I don't see how to do that because the registerApolloClient doesn't take args.

Could you share how to get the client for an Clerk token?

I'm also curious -- where you've said in other posts that registerApolloClient is a singleton, is that also the case on the server only app folder approach?  And if so, how does that work in a multi-user situation where each user has different creds?

**Comment by peterkuykendall** [comment]
ah -- just saw this: https://github.com/apollographql/apollo-client-nextjs/issues/103

**Comment by phryneas** [comment]
> registerApolloClient is a singleton

Yes, but **per request**. Your `registerApolloClient` `makeClient` function will be executed once per request, so you can also just call something like `cookies` in there - you just never ever ever should access the cookies outside of `makeClient` and pass them in via scope or parameters, since then they'll be shared across all requests.

**Comment by peterkuykendall** [comment]
Great, thanks for explaining. I'd appreciate some help here then.

To be totally clear: If you're saying that I shouldn't pass in the cookie outside of makeClient, am I correct in reading that I should also not be setting the cookie with the new:   `client.defaultContext.token = newToken;` in the calling page because there's a possibility that between the setting and the makeClient, it could be set or over-written by another unrelated request?  

If that's the case, then I'm also not clear how to get the jwt from inside of makeClient because I don't see how I can have access to any page, context or cookies there.

**Comment by peterkuykendall** [comment]
wonderful.  Thanks for clarifying how it should be organized. I'm in good shape now.

**Comment by phryneas** [comment]
@shawngustaw that looks good to me, but I have to admit that I am not familiar with your specific way of fetching the token. Glad to hear it works 😊
