### ISSUE TITLE
Large bundle size compared to the standard @apollo/client

### ISSUE THREAD

**Issue by tombryden** [apollographql/apollo-client-nextjs#126]
Hi,

I have noticed when running `npm run build` the first load JS is incredibly large when using any of the hooks from this library when compared with the standard `@apollo/client`

### Import size using 'Import Cost' extension of both the libraries:
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/2a246e19-c5a5-4024-a205-32be904f0d2f)
vs
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/1acda34e-da92-4743-991e-1ab48a18da73)

### npm run build results
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/73e67f7c-97ee-4170-a64c-b33ef53509f7)
vs
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/86cf03eb-f894-45d5-9180-21c6f84062e3)

Thanks

**Comment by phryneas** [comment]
I've seen something similar in #95 where using `NextSSRApolloClient` instead of `ApolloClient` in `registerApolloClient` (so for RSC, not SSR) drove bundle size a lot - is that maybe happening here?

**Comment by tombryden** [comment]
I am using the NextSSRApolloClient, however I just tested with a fresh project and even without any wrapper the package size is 75+kb for any import from `@apollo/experimental-nextjs-app-support/ssr`.

Fresh project, only containing `page.tsx` and `layout.tsx` causes the same issue:

```
"use client";

import { useQuery } from "@apollo/experimental-nextjs-app-support/ssr";

console.log(useQuery);

export default function Home() {
  return (
    <main>
    </main>
  );
}
```

**Comment by tombryden** [comment]
https://github.com/apollographql/apollo-client-nextjs/issues/95#issuecomment-1721965647 - I have also noticed strange behaviour in other instances with bundle sizes.

Just raised a bug with MUI earlier today showing similar behaviour - https://github.com/mui/material-ui/issues/39814

**Comment by tombryden** [comment]
@phryneas I have just re-tested this on 14.0.4 but still the same issue. The MUI bug I mentioned above appears to be fixed on 14.0.4 so I had some hope

**Comment by phryneas** [comment]
Looking into this, this looks like some bug in the next.js build report.

If I build the pages (working with our integration test here), I get these entries in my manifest (`.next/app-build-manifest.json`):

```json
{
  "/cc/dynamic/useSuspenseQuery/page": [
    "static/chunks/webpack-570b061e254f9b2e.js",
    "static/chunks/fd9d1056-2db6654aae4e30bf.js",
    "static/chunks/472-ae7a0071c9c24f93.js",
    "static/chunks/main-app-8059d80e590c3de5.js",
    "static/chunks/521-f6286d24f3481bd1.js",
    "static/chunks/679-3e2ead1f48a6bd5f.js",
    "static/chunks/100-a5bf1a60e71cf4e8.js",
    "static/chunks/app/cc/dynamic/useSuspenseQuery/page-112ed6fcb4431919.js"
  ],
  "/cc/dynamic/useSuspenseQueryAC/page": [
    "static/chunks/webpack-570b061e254f9b2e.js",
    "static/chunks/fd9d1056-2db6654aae4e30bf.js",
    "static/chunks/472-ae7a0071c9c24f93.js",
    "static/chunks/main-app-8059d80e590c3de5.js",
    "static/chunks/521-f6286d24f3481bd1.js",
    "static/chunks/app/cc/dynamic/useSuspenseQueryAC/page-bd72f692458105ca.js"
  ]
}
```
Where `"/cc/dynamic/useSuspenseQuery/page"` uses `import { useSuspenseQuery } from "@apollo/experimental-nextjs-app-support/ssr"` and `"/cc/dynamic/useSuspenseQueryAC/page"` uses `import { useSuspenseQuery } from "@apollo/client";`.

Now you will notice that the import from `@apollo/client` indeed does not contain the two dependencies 
```
    "static/chunks/679-3e2ead1f48a6bd5f.js",
    "static/chunks/100-a5bf1a60e71cf4e8.js",
```
If you look at these, `679-3e2ead1f48a6bd5f` contains the `@apollo/client` package and `100-a5bf1a60e71cf4e8` contains `@apollo/experimental-nextjs-app-support`.

So... The one where we import `@apollo/client` directly does not contain `@apollo/client`. That seems weird. And it is. 
Until you look further, at the layout:

```jsonc
{
    "/cc/layout": [
      "static/chunks/webpack-570b061e254f9b2e.js",
      "static/chunks/fd9d1056-2db6654aae4e30bf.js",
      "static/chunks/472-ae7a0071c9c24f93.js",
      "static/chunks/main-app-8059d80e590c3de5.js",
      "static/chunks/db4cc85f-52d9a110b29d1dde.js",
      "static/chunks/ab91f1f5-c5e022c50fe46f19.js",
      "static/chunks/aaea2bcf-9807dd94c29a0ac5.js",
      "static/chunks/521-f6286d24f3481bd1.js",
      "static/chunks/679-3e2ead1f48a6bd5f.js", // @apollo/client
      "static/chunks/988-f8ecbd3dba53a260.js",
      "static/chunks/100-a5bf1a60e71cf4e8.js", // @apollo/experimental-nextjs-app-support
      "static/chunks/app/cc/layout-a809e480e8f29bda.js"
    ],
}
```

You see: loading the layout already loads those two anyways - no matter which of the two imports we actually use.

So, both of these should actually be equally-sized, until you look at the build report:

```sh
├ λ /cc/dynamic/useSuspenseQuery                       435 B           208 kB
├ λ /cc/dynamic/useSuspenseQueryAC                     5.26 kB         109 kB
```
So, the page `/cc/dynamic/useSuspenseQuery` reports to use 99kb more. But only because it counts one file twice?
If you look further, though, `/cc/dynamic/useSuspenseQueryAC`, by importing from `@apollo/client`, the page size suddenly increased from 435B to 4.26kB. That's because for some reason, here the bundler starts inlining a few functions from `@apollo/client` - from a library that at that point in time has already loaded anyways.

So not only is the reporter broken here, but using `@apollo/client` instead of `@apollo/experimental-nextjs-app-support` actually leads into actual double-shipping of an additional 5kB of code. 🤦

**Comment by phryneas** [comment]
At this point I'm actually not that sure about the tree-shaking here... 

`graphql` should tree-shake down to 12kB (4kB gzipped) for `Kind, visit, print` (which is all that AC uses) or 40kB (10kB gzipped) if you also take into account `parse`, which is used by `graphql-tag`.

But if you look at this, it's 500kB (44kB gzipped) instead, which is crazy!
![image](https://github.com/apollographql/apollo-client-nextjs/assets/4282439/9b01f89b-da10-4437-ad27-b95f3878f1c9)

**Comment by phryneas** [comment]
@tombryden could you give #161 a try? It should shake off a big part of the `graphql` package.

```sh
npm i @apollo/experimental-nextjs-app-support@0.0.0-commit-12fa821
```

**Comment by tombryden** [comment]
Many thanks for looking into this.

I have given this a quick test, this change definitely helps - still not near the size of `@apollo/client` though unfortunately.

### Fresh project, npm run build with Next.js 14.0.4
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/2da36ed4-f38d-4d4d-baad-54764c7ec31c)

### Import Cost Extension (originally 76.6k gzipped so nice improvement here)
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/a689e7ba-5f95-4bcb-9ba0-4f0bc351dbdc)

### npm run build including useQuery from `@apollo/experimental-nextjs-app-support/ssr` (originally 211kB)
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/9c6b500c-319d-415d-8503-5e8c9b9a5817)

### and to compare - regular `@apollo/client` import of `useQuery`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/7a3dafd3-a105-49fd-82f7-1411f785d126)
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/be857ff0-07ab-413d-8ffc-1521cefc1c7b)

**Comment by phryneas** [comment]
@tombryden  I believe your "import cost" calculator makes the same mistake as the Next.js build report itself here - it "forgets" that the layout imports `ApolloClient` etc. anyways - and while those now turn up in your page, they already have been sent to the user with the Layout - this is likely not actually additional bundle size.

Can you measure this another way, e.g. by calling the page in the browser and looking at the actually transmitted data in both cases?

**Comment by tombryden** [comment]
That would make sense, tbh the bundler from next.js 13 onwards seems flaky atm, there are other bugs I am following relating to it.

Here are the results of loading the page:

### `useQuery` from `@apollo/experimental-nextjs-app-support/ssr`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/cb30b57f-75cb-4497-8d0a-376a7205e93a)

### `useQuery` from `@apollo/client`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/3fc02074-4044-4ff9-abf7-9562267ad2cb)

Then I tested using dynamic importing to fully isolate the component with `useQuery`

### Dynamic import with `@apollo/experimental-nextjs-app-support/ssr`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/e1dd27cc-8237-4560-9dbd-207cadc8f274)
Note `_app-pages-browser_src_comps_test_tsx.js` size

### Dynamic import with `@apollo/client`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/d2e0f7c3-8482-4087-a9e9-704aee05444b)



Very strange!

**Comment by phryneas** [comment]
Could it be that you just tried this in dev, not with the `next build`/`next start` artefact? The `page.js` in the `next build` variant is <1kB for me.

**Comment by tombryden** [comment]
Whoops... apologies

Here are the same results using build
### `useQuery` from `@apollo/experimental-nextjs-app-support/ssr`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/5f81d3b6-6d6f-4d2e-9470-a2920cdde224)

### `useQuery` from `@apollo/client`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/76618ec3-d963-49ed-a61f-ea935ea71a99)

### Dynamic import with `@apollo/experimental-nextjs-app-support/ssr`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/0010331b-fe88-422a-a233-a6848b7036d2)

### Dynamic import with `@apollo/client`
![image](https://github.com/apollographql/apollo-client-nextjs/assets/31113935/13eb6459-e949-4e83-8509-400fa5bcce68)

Think you hit the nail on the head - looks like an issue with the bundle reporter

**Comment by phryneas** [comment]
Yeah :/ Unfortunate that Next reports it like that.

But it wasn't for naught - we got that optimization in #161 out of it :)

Are you okay if I close this issue though? I don't think I can really address this from our side.

**Comment by tombryden** [comment]
Will close it now. Many thanks for https://github.com/apollographql/apollo-client-nextjs/pull/161 and looking into this!
