### ISSUE TITLE
Override `fetchOptions` for RSC client

### ISSUE THREAD

**Issue by Pondorasti** [apollographql/apollo-client-nextjs#133]
Is there a way to override Next.js `fetchOptions` on a per request basis when using the [RSC client](https://github.com/apollographql/apollo-client-nextjs#in-rsc)?

For my use case, I retrieve the auth [cookie](https://nextjs.org/docs/app/api-reference/functions/cookies) based on the logged in user and set it as a header to the http link. Since I'm using cookies, Next.js will automatically avoid caching any fetch requests. This works great for auth protected routes. However, I still have 2-3 endpoints that I would like to cache.

```tsx
import { cookies } from 'next/headers'

export const { getClient: getApolloClient } = registerApolloClient(() => {
  const authorizationToken = cookies().get("authorization")?.value;

  return new ApolloClient({
    cache: new InMemoryCache(),
    link: new HttpLink({
      uri: `...`,
      // under the hood, nextjs will set "no-store" due to cookie usage
      // fetchOptions: { cache: "no-store" },
      headers: {
        ...(authorizationToken ? { authorization: `Bearer ${authorizationToken}` } : {}),
      },
    }),
  });
});
```

I've tried overriding the `context` when using `getClient` but it does not seem to respect the props I pass in.

```tsx
getClient().query({
  query,
  variables,
  context: { fetchOptions: { next: { cache: "force-cache", revalidate: 60 } } }, 
});
```

Also tried creating an additional RSC client which did not work either.

```tsx
export const { getClient: getCachedClient } = registerApolloClient(() => {
  return new ApolloClient({
    cache: new InMemoryCache(),
    link: new HttpLink({
      uri: `...`,
      fetchOptions: { cache: "force-cache", revalidate: "60" },
    }),
  });
});
```

**Comment by phryneas** [comment]
That should totally work.

Have you tried overriding the `fetch` link option to `console.log` what is ending up in the `fetch` call?

**Comment by devdumpling** [comment]
```
getClient().query({
  query,
  variables,
  context: { fetchOptions: { next: { cache: "force-cache", revalidate: 60 } } }, 
});
```

Is the `next` here necessary? Looking at the example from the README, it looks like this is the syntax?

```
    // you can override the default `fetchOptions` on a per query basis
    // via the `context` property on the options passed as a second argument
    // to an Apollo Client data fetching hook, e.g.:
    // const { data } = useSuspenseQuery(MY_QUERY, { context: { fetchOptions: { cache: "force-cache" }}});
```

**Comment by phryneas** [comment]
`cache` should just work as a `fetchOption`, since that's a [normal `fetch` option](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache) that Next.js is repurposing. 

But `revalidate` and `tags` are not normal `fetch` options and need to be in `next`: https://nextjs.org/docs/app/api-reference/functions/fetch

**Comment by kopeclu2** [comment]
Any updates ? I have the same issue for ISR
