### ISSUE TITLE
Do we still need to import hooks from experimental-nextjs-app-support/ssr?

### ISSUE THREAD

**Issue by devdumpling** [apollographql/apollo-client-nextjs#139]
I noticed that in the official Apollo docs they no longer say the suspense hooks are experimental (as of 3.8.0)`. In the README for this package there's this snippet:

>You can import the following Apollo Client hooks from "@apollo/experimental-nextjs-app-support/ssr" in your client components (make sure you are not importing these hooks from @apollo/client as this package wraps and re-exports them to support streaming SSR):

Is this still true or are we able to import these hooks from `@apollo/client` if the version is up to date now?

**Comment by devdumpling** [comment]
Similarly, what is the behavior of using `useApolloClient` from `@apollo/client`? Does that need to be imported from `@apollo/experimerntal-nextjs-app-support/ssr` as well?

**Comment by phryneas** [comment]
If a hook is available in `@apollo/experimerntal-nextjs-app-support/ssr`, you have to use that version. 

While the `@apollo/client` hooks are stable to use in a normal React application, they are not meant for streaming SSR (React doesn't have a mechanism for that), to we need to wrap them into Next-specific wrappers that add functionality on top.
