### ISSUE TITLE
Can I prefetch a query which is called at server side on hovering a link or so 

### ISSUE THREAD

**Issue by jinowac** [apollographql/apollo-client-nextjs#140]
Can I prefetch a query which is called at server side on hovering a link or so   
for example  we had like this for client queries from apollo docs  
________________________
```
 const    client  =  useApolloClient()

<Link
            to={{
              pathname: `/${data.breed}/${data.id}`,
              state: { id: data.id }
            }}
            onMouseOver={() =>
              client.query({
                query: GET_DOG,
                variables: { breed: data.breed }
              })
            }
            style={{ textDecoration: "none" }}
          >
            <Dog {...data} url={data.displayImage} />
         </Link>

```
----------------------------------------------------------------------------------------------------------

@phryneas can u help me in with to prefetch the query called at server side on hovering a link  when we are using this new "@apollo/experimental-nextjs-app-support/ssr" . Prefetching the query will help me to land to the page instantaneously

**Comment by phryneas** [comment]
You would do exactly that. After the first page load, there is no further SSR in Next.js, so nothing changed here.

**Comment by jinowac** [comment]
@phryneas  what do you suggest . what cud be done?

**Comment by phryneas** [comment]
Ah, wait a second, you mean "server side", so we're talking RSC here, not SSR? 
Next.js already does this for RSC page navigations if you use their `Link` component, nothing for you to do.

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.
