### ISSUE TITLE
useSuspenseQuery Apollo Error Unexpected token "<"

### ISSUE THREAD

**Issue by Melihkrkvk** [apollographql/apollo-client-nextjs#145]
I am using Next.js with the Apollo Client in my app directory. When I make an API call using `useSuspenseQuery`, I encounter an error. Upon the error appearing, if I refresh the page, the error disappears, and everything works smoothly. The same error repeats with each request. However, when I use `getClient` to make the same query, there is no issue. Does anyone have a solution for this?

### Error
![Ekran Alıntısı](https://github.com/apollographql/apollo-client-nextjs/assets/86918877/f3ac6d74-b3f7-455e-bcd6-bc19e76ed130)
### Usage
![Ekran Alıntısı2](https://github.com/apollographql/apollo-client-nextjs/assets/86918877/3b3dc15e-250d-4a6c-b590-197a510f42c7)
### If I use getClient I don't get any errors
![Ekran Alıntısı3](https://github.com/apollographql/apollo-client-nextjs/assets/86918877/f3517bb4-948d-49d6-89b5-47f9bdd3fdc8)
### getClient.tsx
![Ekran Alıntısı5](https://github.com/apollographql/apollo-client-nextjs/assets/86918877/c3ebc4ee-3cdd-4a97-9ec0-103dcd5cdc83)
### ApolloWraper.tsx
![Ekran Alıntısı6](https://github.com/apollographql/apollo-client-nextjs/assets/86918877/8d9d7b80-87e2-4c81-b089-829ca7cb7d56)
### layout.tsx
![Ekran Alıntısı7](https://github.com/apollographql/apollo-client-nextjs/assets/86918877/e613534d-1601-4e25-a4d9-c95a23b10fa0)
### Dependencies
![Ekran Alıntısı4](https://github.com/apollographql/apollo-client-nextjs/assets/86918877/df7f9fef-4e57-4455-848b-0fbc6a71b1cb)

**Comment by phryneas** [comment]
Two questions:
* where do you import `useSuspenseQuery` from?
* is your BACKEND_API maybe not reachable from the server? It looks like the server tries to make a request there and gets a HTML response instead of GraphQL JSON.

**Comment by Melihkrkvk** [comment]
> Two questions:
> 
> * where do you import `useSuspenseQuery` from?
> * is your BACKEND_API maybe not reachable from the server? It looks like the server tries to make a request there and gets a HTML response instead of GraphQL JSON.

Thank you for answer. I import llike this `import { useSuspenseQuery } from '@apollo/experimental-nextjs-app-support/ssr';` and I don't think BACKEND_API not reachable. Because if I refresh the page after getting the error, it gets fixed. and when I use it with `getClient` there is no problem. I'm only having a problem with `useSuspenseQuery`

**Comment by phryneas** [comment]
Hmm, that sounds the other way round - like you browser cannot access the api, but the server can.

Can you check your network devtools if the requests actually go through in that error case?

I believe your environment variable might be at fault here

To quote the [Next.js docs](https://nextjs.org/docs/messages/missing-env-value):

> When accessing environment variables on the client they must be prefixed with NEXT_PUBLIC_ to signify they are safe to be inlined for the client.

**Comment by Melihkrkvk** [comment]
when we use 'use client' directive .env working with that error. I added `env:{
'customKey': backendApi
}`
to next.config.js than it worked for me
