### ISSUE TITLE
What is the `useLazyQuery` alternative to useSuspense and `useBackgroundQuery`?

### ISSUE THREAD

**Issue by sa-ma** [apollographql/apollo-client-nextjs#150]
`useLazyQuery` allowed us to fetch data when it was needed and not at runtime but I don't see a way to do that with `useSuspense`. I tried the `skipToken` on `useBackgroundQuery` but the companion `useReadQuery` throws a Typescript error saying `queryRef` cannot be `undefined`

**Comment by jerelmiller** [comment]
Hey @sa-ma 👋 

We have a new hook coming in 3.9 called [`useLoadableQuery`](https://github.com/apollographql/apollo-client/pull/11300) that I think is what you're looking for. We should be releasing this in the next alpha version if you're interested in trying it out!

**Comment by sa-ma** [comment]
> Hey @sa-ma 👋
> 
> We have a new hook coming in 3.9 called [`useLoadableQuery`](https://github.com/apollographql/apollo-client/pull/11300) that I think is what you're looking for. We should be releasing this in the next alpha version if you're interested in trying it out!

I will. Thanks.

**Comment by phryneas** [comment]
Apollo Client 3.9 has been released with `useLoadableQuery`, so I think this has been answered sufficiently :)
