### ISSUE TITLE
Can race conditions occur with useSuspense when only using SSR?

### ISSUE THREAD

**Issue by jsindos** [apollographql/apollo-client-nextjs#153]
The last time I used Next.js / SSR was before `useSuspense` was introduced. I'm planning on only using this library with SSR, and not using RSC at all.

I'm wondering if the following warning from the README applies to `useSuspense` with SSR, i.e. is it possible for client components to render while other components are still SSR? As far as I understand this should not be possible.

>❗️ This package is experimental. Generally it should work well, you might run into race conditions when your Client Component is still rendering in SSR, and already making overlapping queries on the browser.
This cannot be addressed from our side, but would need API changes in Next.js or React itself.
If you do not use suspense in your application, this will not be a problem to you.

**Comment by phryneas** [comment]
The same subtree should not render, but since Next.js streams data immediately and incrementally hydrates your UI, a very deeply nested suspense boundary can still be loading on the server while the client is (apart from that one subtree) already fully interactive.

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.
