### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by kamalkech** [apollographql/apollo-client-nextjs#157]
where is documentation about who can use subscription with @apollo/experimental-nextjs-app-support/ssr ?????

**Comment by phryneas** [comment]
On the server, you can't use subscriptions - React renders once, and then flushes things to the browser. Your first subscription result would likely arrive long after the server stopped rendering that component.

In the browser, though, you can totally use it.

That means that you can use the `useSubscription` hook of `@apollo/client`, with one small change: skip it during SSR.

```js
function MyComponent() {
  const { data, loading } = useSubscription(MySubscription, {
    skip: typeof window == "undefined",
  });
  // other logic
}
```

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.
