### ISSUE TITLE
Cookie is not accessible by registerApolloClient

### ISSUE THREAD

**Issue by Eprince-hub** [apollographql/apollo-client-nextjs#159]
The GraphQL context setup in the handler always returns undefined pages that use the `getClient()` functions. The `getClient()` is set with the code below.

```ts
import { ApolloClient, HttpLink, InMemoryCache } from '@apollo/client';
import { registerApolloClient } from '@apollo/experimental-nextjs-app-support/rsc';
import { headers } from 'next/headers';

export const { getClient } = registerApolloClient(() => {
  const link = new HttpLink({
    uri: 'http://localhost:3000/api/graphql',
    credentials: 'same-origin',
  });

  // headers();
  return new ApolloClient({
    cache: new InMemoryCache(),
    link,
  });
});
```
The context is set in the `startServerAndCreateNextHandler()` this way

```ts
const handler = startServerAndCreateNextHandler<NextRequest>(apolloServer, {
  context: async (req) => {
    const fakeSessionToken = req.cookies.get('fakeSession');
    console.log('fakeSessionToken', fakeSessionToken);

    return {
      req,
      fakeSessionToken,
    };
  },
});
```
Every `console.log` of the `context.fakeSessionToken` on every query returns undefined when the query only uses the `getClient()` function. The `fakeSessionToken` is also undefined within the context when the query is a `getClient()`

The expected result of `fakeSessionToken` is logged into the console whenever a mutation operation is performed.

### How to reproduce

[Repro Repository](https://github.com/Eprince-hub/graphql-context-repro.git) 

1. Clone the above repository
```bash
git clone https://github.com/Eprince-hub/graphql-context-repro.git
```
2. Move into the folder and run the project
```bash
cd graphql-context-repro
```
3. Install dependencies
```bash
pnpm i
```
4. Start the project
```bash
pnpm dev
```
**OR**: Run all the above commands with
```bash
git clone https://github.com/Eprince-hub/graphql-context-repro.git && cd graphql-context-repro && pnpm i &&  pnpm dev
```
5. Visit the website at `http://localhost:3000/`
6. Open up your console so that you can see the console.logs
7. Click on the `login` button to create the cookies
8. Click on the `View animals` navigation to move to the animals page
**NOTE**: This page uses `getClient()` query, so the `fakeSessionToken` context will be undefined even though it exists on the browser
9. Navigate to the `Create animal` and click on the `Create Animal` button
**NOTE**: The `fakeSessionToken` will have the expected value at this time

The `home/login` and the `create animal` pages use mutation and always log the correct value of the cookies to the console, but the `/animals` that use the `getClient()` always logs undefined. In my main project, this behavior is the same for all the pages, where only `getClient()` is used

### Expected behavior
1. That context returns the cookie's value also when being accessed by the `getClient()` function
2. That all resolvers should get the correct value for the context at all time, instead of the undefined

This causes many issues when we need to authenticate a user via the context object on queries.

I think it is slightly related to this issue https://github.com/apollographql/apollo-client-nextjs/issues/21, but not exactly

**Comment by phryneas** [comment]
If you use React Server Components, you send a request from your server to your server. These requests do not automatically contain any cookies, as they would be sent from a browser to the server.

You will need to manually load these cookies in a custom `setContext` link by calling the [`cookies`](https://nextjs.org/docs/app/api-reference/functions/cookies) function of Next.js and manually set the cookies that you want to forward in that link.

**Comment by Eprince-hub** [comment]
@phryneas, Thank you so much for your reply. Following the documentation [here](https://www.apollographql.com/docs/react/api/link/apollo-link-context/ ) I tried to set the context in the Apollo client like this 

```ts
const browserCookies = setContext(() => {
  return {
    headers: {
      cookies: cookies().get('fakeSession'),
    },
  };
});

export const { getClient } = registerApolloClient(() => {
  const link = new HttpLink({
    uri: 'http://localhost:3000/api/graphql',
    credentials: 'same-origin',
  });

  headers();
  return new ApolloClient({
    cache: new InMemoryCache(),
    link: browserCookies.concat(link),
  });
});
```

But I am still getting it as undefined, maybe this is not the right way to do it

Can you please, let me know the right way to get this work? Must I send the cookies with the request? I would appreciate it if there is an example that can clear things out a little bit more

**Comment by phryneas** [comment]
I believe you would need to do something along the lines of

```js
const browserCookies = setContext(() => {
  return {
    headers: {
      cookie: `fakeSession=${cookies().get('fakeSession')};`
   },
  };
});
```

**Comment by Eprince-hub** [comment]
Thanks for the feedback. Helped a lot. Setting up the `getClient()` as shown below solved my issue

```ts
const browserCookies = setContext(() => {
  return {
    headers: {
      cookie: `fakeSession=${cookies().get('fakeSession')?.value}`,
    },
  };
});

export const { getClient } = registerApolloClient(() => {
  const link = new HttpLink({
    uri: 'http://localhost:3000/api/graphql',
    credentials: 'same-origin',
  });

  return new ApolloClient({
    cache: new InMemoryCache(),
    link: browserCookies.concat(link),
  });
});
```
I can now set the cookie context in the `handler` and have access to it in every resolver

```ts
const handler = startServerAndCreateNextHandler<NextRequest>(apolloServer, {
  context: async (req) => {
    const fakeSessionToken = req.cookies.get('fakeSession');
    console.log('fakeSessionToken', fakeSessionToken);
    return {
      req,
      fakeSessionToken,
    };
  },
});
```
With this update, I will be closing this issue, as I am not having the problem anymore
Thank you🙏
