### ISSUE TITLE
i want to pass the params through getClient

### ISSUE THREAD

**Issue by VolcanoDiver** [apollographql/apollo-client-nextjs#175]
how do i pass the token data to getClient so that i can add auth headers to ApolloLink?

**Comment by phryneas** [comment]
Most likely, you shouldn't go about it that way.

If you want to specify your authentication headers at call site, you can do so by providing `context`:

```js
getClient().query({
  query,
  context: { headers: { authentication: "..." } },
});
```

Or (and this is probably what you will do instead in most cases), you can just call `cookies` (or whatever other way of getting your auth headers you have) [inside of a setContext link](https://www.apollographql.com/docs/react/networking/authentication/#header)

```js
export const { getClient } = registerApolloClient(() => {
  const httpLink = createHttpLink({
    uri: "/graphql",
  });

  const authLink = setContext((_, { headers }) => {
    const token = cookies().get("myCookie");
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : "",
      },
    };
  });

  return new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache(),
  });
});
```

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.
