### ISSUE TITLE
RSC getClient() not working with Next 14

### ISSUE THREAD

**Issue by ninibear030** [apollographql/apollo-client-nextjs#179]
i am using next 14.0.4
"@apollo/client": "3.9.0-rc.1",
"@apollo/experimental-nextjs-app-support": "^0.6.0",
 tutorial link: https://www.apollographql.com/blog/using-apollo-client-with-next-js-13-releasing-an-official-library-to-support-the-app-router

when I use it in my RSC i get error:
```
'server-only' cannot be imported from a Client Component module. It should only be used from a Server Component.
The error was caused by importing '@apollo/experimental-nextjs-app-support/dist/rsc/index.js' in '../../...'.
```

**Comment by phryneas** [comment]
That error message states that you are importing Server Component functionality in a Client Component. Are you sure that the file you are importing into is not a Client Component?

**Comment by ninibear030** [comment]
I used that in the page.tsx, I don't think its possible for it to be client side. 😞😭

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.

**Comment by gersongams** [comment]
I'm having the same issue 😢

**Comment by phryneas** [comment]
@gersongams that means that you are importing a file that contains `registerApolloClient` from a Client component. 
That could also happen over a few corners - you import a file from a `"use client"` file that imports a file that imports a file that imports `registerApolloClient`.

That's not allowed in Next.js - things meant for the server have to stay on the "server side" of imports and things meant for the client have to stay on the "client side" of imports.
