### ISSUE TITLE
How to pass data into layout.tsx?

### ISSUE THREAD

**Issue by iuadastra** [apollographql/apollo-client-nextjs#26]
In Next.js App Router app, that uses layout.tsx, how is it possible to pass data from page.tsx to layout.tsx?

Consider this situation: I am using client side Apollo client with SSR. I have a big query that contains some data for page directly and some data for layout that are specified using fragment imported from layout. I load the data in page.tsx. Now how do I pass the data from fragment to layout?

**Comment by patrick91** [comment]
as far as I know there's no way of doing this, the only way would be to fetch the data directly from the layout file 😊

**Comment by phryneas** [comment]
Yeah, as far as I know those are either rendered independently, or the Layout is rendered as a parent of the Page, so unfortunately, data won't be able to flow in that direction.

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.
