### ISSUE TITLE
Attempted import error: 'registerApolloClient' is not exported from '@apollo/experimental-nextjs-app-support/rsc' (imported as 'registerApolloClient').

### ISSUE THREAD

**Issue by Whitebytes** [apollographql/apollo-client-nextjs#289]
to reproduce:

npx create-next-app@latest
 What is your project named? ... my-app
√ Would you like to use TypeScript? ... No
√ Would you like to use ESLint? ... No 
√ Would you like to use Tailwind CSS? ... No
√ Would you like to use `src/` directory? ... Yes
√ Would you like to use App Router? (recommended) ... Yes
? Would you like to customize the default import alias (@/*)? » No

npm install @apollo/client@latest @apollo/experimental-nextjs-app-support graphql

Seems to me incompatability when using nextjs without typescript.
When installing Nextjs with typescript, the error dont exist.

**Comment by phryneas** [comment]
This should not have anything to do with TypeScript or not TypeScript.

You will get this error message if you import `registerApolloClient` from a `"use client"` file or a file that is imported from a `"use client"` and so on.

`registerApolloClient` is only exported in a React Server Component context, just like `useState` is only exported from `react` in a `"use client"` context, but not in a RSC context.

**Comment by Whitebytes** [comment]
ok, can confirm this was the issue, thanx. Nature of the error gave me not any clue this was a ssr issue.. (like the one you get when using useState while ssr)..

**Comment by leonchabbey** [comment]
@phryneas I'm having the same issue when using the RSC client from the middleware. Not sure whether that's a bug in the library and this RSC client is not compatible with the middleware's context?

**Comment by leonchabbey** [comment]
I think i got my answer there: https://github.com/apollographql/apollo-client-nextjs/issues/280#issuecomment-2059443275
So the client doesn't seem to have middleware support

**Comment by phryneas** [comment]
Yeah, middleware are yet another layer of Next.js that lives outside of the React world. Just create a new ApolloClient instance inside of your middleware - there's no extra support or orchestration needed from our side.

(If we find a way of making this nicer, we'll look into that, but no guarantees when that can happen)
