### ISSUE TITLE
Getting error when upgrading @apollo/client package

### ISSUE THREAD

**Issue by elrumordelaluz** [apollographql/apollo-client-nextjs#295]
Everything was working ok following the README docs until upgraded `@apollo/client` from `v3.9.11` into the [last minor releases](https://github.com/apollographql/apollo-client/releases/tag/v3.10.3), like `v3.10.x`, getting this error:

> Internal error: Error: When using `ApolloClient` in streaming SSR, you must use the `NextSSRApolloClient` export provided by `"@apollo/experimental-nextjs-app-support/ssr"`

Seems that this packages is using the previous minor releases of `@apollo/client` as [devDependency](https://github.com/apollographql/apollo-client-nextjs/blob/main/packages/experimental-nextjs-app-support/package.json#L82) and [peerDependency](https://github.com/apollographql/apollo-client-nextjs/blob/main/packages/experimental-nextjs-app-support/package.json#L113). 

For now I am fixing the `@apollo/client` version into `v3.9.x` but just wondering if is it planned to support new versions (in case this is the problem and not something I am missing).

**Comment by phryneas** [comment]
The lastest version of Apollo Client is definitely supported - `^3.9.6` includes `3.10.*`.

Can you please how your setup for this package, including all the import statements?

**Comment by elrumordelaluz** [comment]
Thank you @phryneas. I must apologize for opening the issue regarding package versions without first doing this test:

```
rm -rf node_modules pnpm-lock.yaml
```

which makes everything working again. Seems there was an issue related on `pnpm` cache/store which was solved as described. Thank you again!
