### ISSUE TITLE
URI not considered

### ISSUE THREAD

**Issue by ludoblues** [apollographql/apollo-client-nextjs#308]
I am trying to config the lib on a brand new project but when i perform a mutation, the request hits localhost (don't consider the uri i pass when configuring the client).

It looks like i am doing like the examples:

ApolloWrapper.tsx
``` typescript
"use client";

import { ApolloLink, HttpLink, concat } from "@apollo/client";
import {
  ApolloNextAppProvider,
  ApolloClient,
  InMemoryCache,
  SSRMultipartLink,
} from "@apollo/experimental-nextjs-app-support";

function makeClient() {
  const httpLink = new HttpLink({
    uri: "http://test.com",
    fetchOptions: { cache: "no-store" },
  });

  return new ApolloClient({
    cache: new InMemoryCache(),
    link: httpLink,
  });
}

export function ApolloWrapper({ children }: React.PropsWithChildren) {
  return (
    <ApolloNextAppProvider makeClient={makeClient}>
      {children}
    </ApolloNextAppProvider>
  );
}
```

layout.tsx
``` typescript
  return (
    <html suppressHydrationWarning={true} lang="fr">
      <body className={inter.className}>
          <ApolloWrapper>
            <AuthProvider initialUser={user}>
              <ResponsiveAppBar />
              {children}
            </AuthProvider>
          </ApolloWrapper>
      </body>
    </html>
  );
}
```

folder/page.tsx
``` typescript
import { gql, useMutation } from "@apollo/client";

export default function AddTodoPage() {
  const [addTodo, { data, loading, error }] = useMutation(ADD_TODO);

  try {
    addTodo({}); // localhost instead of test.com
  } catch(e) {
    // ...
  }
}
```

**Comment by ludoblues** [comment]
For debugging i have really hardcoded "http://test.com" be see if it would be reflected in the network when performing the mutation call and i see "localhost" instead.

**Comment by phryneas** [comment]
Phew, that's extremely weird - that code hasn't been touched in years and  together with the Apollo Client core library, probably millions of devs are running this. Really all I can think of would be next not correctly bundling the environment variable.

Does is still log correctly of you put that `console.log` into the `makeClient` function?

**Comment by ludoblues** [comment]
I could have it work by manually rebuild my stack
I definitely have an issue with my hot reload which doesn't affect all the changes

Thanks for your time!

**Comment by phryneas** [comment]
Great to hear that everything worked out :)

**Comment by takuyawww** [comment]
the same problem is reproduced in the local environment.
Is there currently no way around this other than hard-coding the specification to the uri?
