### ISSUE TITLE
PreloadQuery typescript error

### ISSUE THREAD

**Issue by jovanblazek** [apollographql/apollo-client-nextjs#314]
When exporting  `PreloadQuery` from `registerApolloClient` I am getting the following typescript error.
```
Exported variable 'PreloadQuery' has or is using name 'PreloadQueryComponent' from external module "<path>/node_modules/@apollo/client-react-streaming/dist/combined" but cannot be named.
```

Code: (same as in readme)
```ts
export const { getClient, query, PreloadQuery } = registerApolloClient(
  () =>
    new ApolloClient({
      cache: new InMemoryCache(),
      link: new HttpLink({
        uri: 'http://example.com/api/graphql',
      }),
    })
)
```

**Comment by phryneas** [comment]
Hmm, that could happen if you have `declarations: true` in your `tsconfig.json` and don't explicitly add `@apollo/client-react-streaming` to your dependencies (which you shouldn't need to).
I'll see that I re-export that type.

**Comment by phryneas** [comment]
Could you please try this build from #315  and report back if it fixes your problem?
```js
npm i @apollo/client-react-streaming@0.0.0-commit-release.0.1718188292.62716af
```

**Comment by jovanblazek** [comment]
@phryneas That fixed it 🚀
