### ISSUE TITLE
Do `SeenWrappers` and `SeenClients` grow indefinitely?

### ISSUE THREAD

**Issue by devdumpling** [apollographql/apollo-client-nextjs#321]
While I was looking into how you all implement `registerApolloClient` I noticed [there are two Sets](https://github.com/apollographql/apollo-client-nextjs/blob/e7a59cb26716a77bbfac659f435f89f5af8eff61/packages/client-react-streaming/src/registerApolloClient.tsx#L9) that act as a check to make sure that clients aren't being instantiated across requests. Do you all know if these grow indefinitely or do they get garbage collected somehow?

I do a custom deployment for Next, so I have a long-running node process for the server. This would grow in memory over time with requests if it isn't pruned every now and then, no?

----

> Below is context to why I was poking around in the first place.

I've been poking around in the code a bit to try and get a setup that would allow me to effectively parameterize the creation of the RSC apollo client. The use case here is I have some pages that might want a different set of headers. I could pass the different set to each query within that page at the query level, but I was exploring simply allowing for programmatically registering the client. 

Something like 

```
// Return a memoized RSC ApolloClient that overrides the default options
export function customGetClient(config: any) {
  return registerApolloClient(() => {
    return new ApolloClient({
      cache: new InMemoryCache(),
      name: config.name ?? 'next-web-custom-rsc',
      link: new HttpLink({
        uri: STITCHER_SSR_URL,
        fetchOptions: { cache: 'no-store' },
      }),
    });
  });
}
```

This doesn't seem to work though. It ends up creating a new ApolloClient every time this function is called, which I now see is based on my misunderstanding of how react.cache works. Seems like best we can do without adding another layer of react.cache would be to simply pass config directly in at the query level instead.

**Comment by devdumpling** [comment]
(also thank you for always answering my questions 🙏)

**Comment by devdumpling** [comment]
TIL about [WeakSet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet), which says it's garbage collected. So maybe this is a non-issue?

**Comment by phryneas** [comment]
Sorry for the slow response, I was off for a day.

You're right with your second observation here - `WeakSet` and `WeakMap` don't keep values in memory like their `Set` and `Map` counterparts. That makes them awkward to work with (you won't be able to iterate the values of a `WeakSet`) but in this specific use case of "have we already seen this thing?", they're excactly what's needed to implement the check here without a memory leak.

As for your problem at hand - could you create `config` inside of `makeClient`? It's perfectly fine for example to make a call to `cookies` in there.
Note though that that would always make your site generation dynamic. If you don't want that, you could call `registerApolloClient` twice, once for a version that doesn't access `cookies`, and once for a version that does.

**Comment by devdumpling** [comment]
No worries! Hope you enjoyed your time off. Thanks for responding!

> As for your problem at hand - could you create config inside of makeClient? It's perfectly fine for example to make a call to cookies in there.
Note though that that would always make your site generation dynamic. If you don't want that, you could call registerApolloClient twice, once for a version that doesn't access cookies, and once for a version that does.

This is exactly what we ended up doing. I basically set up two registration exports, one which is intended for dynamic use and exports the default `{ query, getClient, PreloadQuery }` and then another that does not use `cookies` or `headers` and is exported as ` { cachedQuery, getCachedClient, PreloadCachedQuery }`. This feels explicit enough to me that devs won't confuse it much, and we can pass config options and headers as needed to the query or client itself (via links or `context`).

**Comment by phryneas** [comment]
That seems like a good solution :)

As all questions seem to be answered, I'm going to close the issue here. Have a great day!
