### ISSUE TITLE
Not sending data to the client.

### ISSUE THREAD

**Issue by nitedani** [apollographql/apollo-client-nextjs#325]
I am trying to integrate this with 
- vite
- [vike](https://github.com/vikejs/vike)
- https://github.com/brillout/react-streaming

It's almost working, my code looks like this:
```tsx
import { WrapApolloProvider } from '@apollo/client-react-streaming'
import { buildManualDataTransport } from '@apollo/client-react-streaming/manual-transport'
import { useStream } from 'react-streaming'
import { renderToString } from 'react-dom/server'
import React from 'react'

export const WrappedApolloProvider = WrapApolloProvider(
  buildManualDataTransport({
    useInsertHtml() {
      const stream = useStream()
      if (!stream) {
        return () => {}
      }
      return (callback: () => React.ReactNode) => {
        const reactNode = callback()
        const injectionsString = renderToString(reactNode)
        console.log({ reactNode, injectionsString })
        stream.injectToStream(injectionsString)
      }
    }
  })
)
```

Issue: the data is not sent to the client. The output of the `console.log` above is the following:
```
{
  reactNode: {
    '$$typeof': Symbol(react.transitional.element),
    type: [Function: RehydrateOnClient],
    key: null,
    props: {},
    _owner: null,
    _store: {}
  },
  injectionsString: ''
}
{
  reactNode: {
    '$$typeof': Symbol(react.transitional.element),
    type: [Function: RehydrateOnClient],
    key: null,
    props: {},
    _owner: null,
    _store: {}
  },
  injectionsString: '<script>(window[Symbol.for("ApolloSSRDataTransport")] ??= []).push({"rehydrate":{},"events":[{"type":"started","options":{"fetchPolicy":"cache-first","query":"query Dragons{dragons{name first_flight diameter{feet}launch_payload_mass{lb}}}","notifyOnNetworkStatusChange":false,"nextFetchPolicy":undefined},"id":"1"}]})</script>'
}
{
  reactNode: {
    '$$typeof': Symbol(react.transitional.element),
    type: [Function: RehydrateOnClient],
    key: null,
    props: {},
    _owner: null,
    _store: {}
  },
  injectionsString: ''
}
{
  reactNode: {
    '$$typeof': Symbol(react.transitional.element),
    type: [Function: RehydrateOnClient],
    key: null,
    props: {},
    _owner: null,
    _store: {}
  },
  injectionsString: '<script>(window[Symbol.for("ApolloSSRDataTransport")] ??= []).push({"rehydrate":{},"events":[{"type":"complete","id":"1"}]})</script>'
}
```

As you can see, the callback is called 4 times, but it produces only 2 script tags, with no data included.
![image](https://github.com/apollographql/apollo-client-nextjs/assets/67418286/3e949bed-2ed2-4639-8600-aab153d68638)

**Comment by nitedani** [comment]
I can prepare a reproduction if it would help.

**Comment by nitedani** [comment]
It works in your vite example because `renderInjectedHtml` is called with `await`, so it executes after `Reflect.set(...args)`, even if there is no async call inside.
https://github.com/apollographql/apollo-client-nextjs/blob/e7a59cb26716a77bbfac659f435f89f5af8eff61/packages/client-react-streaming/src/stream-utils/createInjectionTransformStream.tsx#L91


This is the cause:
https://github.com/apollographql/apollo-client-nextjs/blob/e7a59cb26716a77bbfac659f435f89f5af8eff61/packages/client-react-streaming/src/ManualDataTransport/RehydrationContext.tsx#L102
Why is this not:
```ts
function getTransportObject(ensureInserted: () => void) {
  return new Proxy(
    {},
    {
      set(...args) {
		const ret = Reflect.set(...args);
        ensureInserted();
        return ret;
      },
    }
  );
}
```

**Comment by nitedani** [comment]
I figured it out, the following works:
Just needed to add `await` in front of the `callback`. 😄 Had to dig a little.

```tsx
import { WrapApolloProvider } from '@apollo/client-react-streaming'
import { buildManualDataTransport } from '@apollo/client-react-streaming/manual-transport'
import { useStream } from 'react-streaming'
import { renderToString } from 'react-dom/server'
import React from 'react'

export const WrappedApolloProvider = WrapApolloProvider(
  buildManualDataTransport({
    useInsertHtml() {
      const stream = useStream()
      if (!stream) {
        return () => {}
      }
      return async (callback: () => React.ReactNode) => {
        const reactNode = await callback()  // <--- added await
        const injectionsString = renderToString(reactNode)
        stream.injectToStream(injectionsString)
      }
    }
  })
)
```

**Comment by phryneas** [comment]
Hmm... I believe what you have here doesn't work:
```
return async (callback: () => React.ReactNode) => {
        const reactNode = await callback()  // <--- added await
        const injectionsString = renderToString(reactNode)
        stream.injectToStream(injectionsString)
      }
```

This delays the injection into the stream - but without blocking the stream, so React will already start to stream content that depends on the value that will only be injected later.

You'd need to pause the stream, await, inject, and then resume normal stream functionality.

**Comment by brillout** [comment]
Thanks for your answer, that makes sense.

I'm currently working on fixing it (I'm very looking forward to `vike-react-apollo`) but I'm having issues because the injected chunks are being inserted in the wrong place.

Is there a rule of when it's allowed to inject to the stream? I've yet to read an official guide from React about this.

> PS: super cool to see more people playing with this! Please share your final result - maybe we can even add it as another integration test?

Apollo has quite a lot of goodies to make integration easy, it's quite neat. And, yes, we'd be up for an integration test!

**Comment by phryneas** [comment]
There's no official guidance on when it is safe to inject - our [`createInjectionTransformStream`](https://github.com/apollographql/apollo-client-nextjs/blob/3e169acdba774161c52f8c4df0eebc41e4b86f6f/packages/client-react-streaming/src/stream-utils/createInjectionTransformStream.tsx) is based on the [implementation from Next.js](https://github.com/vercel/next.js/blob/6481c92038cce43056005c07f80f2938faf29c29/packages/next/src/server/node-web-streams-helper.ts) in the hopes that they know what they are doing.

Generally: it seems that React might inject multiple chunks that belong together, but always does so synchronously. So waiting for the next `Promise.resolve().then` or similar should always give you a safe point in time to inject.

**Comment by phryneas** [comment]
Generally, did you see https://github.com/apollographql/apollo-client/pull/11807/files#diff-bd3d926d0da12f95cf1980b882dc8bb6f70b4e542f3673ea96f0bb21c281118f ?

**Comment by brillout** [comment]
>  it seems that React might inject multiple chunks that belong together, but always does so synchronously

That was my guess as well. ([Funny coincidence](https://github.com/brillout/react-streaming/pull/42/commits/e1f3ae88084087f64999aac57bbaaf0e835f2a99).)

Good to know that I ain't alone with my guess.

> Generally, did you see https://github.com/apollographql/apollo-client/pull/11807/files#diff-bd3d926d0da12f95cf1980b882dc8bb6f70b4e542f3673ea96f0bb21c281118f ?

I didn't yet but I guess @nitedani did.

**Comment by brillout** [comment]
> Generally: it seems that React might inject multiple chunks that belong together, but always does so synchronously. So waiting for the next `Promise.resolve().then`, `setImmediate` or similar should always give you a safe point in time to inject.

FYI that's what [`react-streaming`](https://github.com/brillout/react-streaming) originally did, but I moved away from this approach. Instead, whenever React writes, `react-streaming` synchronously adds React's chunk to its internal buffer (an array of chunks), so that injection order is respected. I find this approach a lot more reliable and flexible, and easier to reason about.

**Comment by phryneas** [comment]
> FYI that's what [`react-streaming`](https://github.com/brillout/react-streaming) originally did, but I moved away from this approach. Instead, whenever React writes, `react-streaming` synchronously adds React's chunk to its internal buffer (an array of chunks), so that injection order is respected. I find this approach a lot more reliable and flexible, and easier to reason about.

Interesting!

Tbh., I don't really want to overengineer that part. 
For what we are doing, I see it as a crutch we have to use until React gets their story on stream injection of values from SSR to the Browser in place. I still hope that we'll get an early React 19.x minor that has that functionality natively and then we can drop it.

**Comment by brillout** [comment]
> I still hope that we'll get an early React 19.x minor that has that functionality natively and then we can drop it.

Me too, although I haven't heard any news about this nor [injectToStream](https://github.com/reactjs/rfcs/pull/219).

**Comment by phryneas** [comment]
Last I heard from the team they were trying to find more granular things than an `injectToStream` helper, but I have no idea on their current stance.

I tried to hack together my "optimal" api by just editing React sources, and have multiple attempts, if you're interested in the exploration :)

* First attempts were a bit wonky, but I got them working: https://x.com/phry/status/1724028460966781317
* My latest attempt is still in the air since I just moved and have a little puppy here now that takes all my time and attention, but this is the api design I'd go for: https://x.com/phry/status/1796309546136133748

**Comment by brillout** [comment]
I guess we can close this (I can't do it as I ain't OP), thank you @phryneas for your help!

**Comment by phryneas** [comment]
Good call - I believe the release of this was just announced at https://x.com/vike_js/status/1813474021201027129, so I'm going to close this here :)
