### ISSUE TITLE
Data in polls-demo example rsc query has type "any"

### ISSUE THREAD

**Issue by joelhoelting** [apollographql/apollo-client-nextjs#33]
Hello, I was reading through this blog post: https://www.apollographql.com/blog/announcement/frontend/using-apollo-client-with-next-js-13-releasing-an-official-library-to-support-the-app-router/

We have the following code in `apollo-client-nextjs/examples/polls-demo/app/rsc/page.tsx`:

```
import { getClient } from "./client";
import { Poll } from "./poll-rsc";
import { ApolloWrapper } from "../cc/apollo-wrapper";
import { GetPollDocument } from "@/components/poll/documents.generated";

export const dynamic = "force-dynamic";

export default async function Page() {
  const data = await getClient().query({
    query: GetPollDocument,
    variables: { id: "1" },
  });

  // we are using Apollo Wrapper here too so we can use
  // useMutation in the Poll component
  return (
    <ApolloWrapper>
      <Poll poll={data.data.poll!} />
    </ApolloWrapper>
  );
}
```

The `data` variable in `const data = await getClient()` has an implicit type `any`. Is there a step missing to get types working correctly for this example?

**Comment by phryneas** [comment]
If you clone the whole repo, you might need to build the package once (this is a `prebuild` trigger, but you can also do `yarn workspace @apollo/experimental-nextjs-app-support build`). Then everything should work out for you.

This is what it looks like for me:

![image](https://github.com/apollographql/apollo-client-nextjs/assets/4282439/735a74e7-54bd-481e-a639-a4fe3ba388f2)

**Comment by joelhoelting** [comment]
Thanks, that worked!
