### ISSUE TITLE
Export of symbols for test resets?

### ISSUE THREAD

**Issue by luchillo17** [apollographql/apollo-client-nextjs#34]
# Problem

I am probably doing something weird to have a wrapper defined in an NX monorepo & have it tested like this, but so far this is the most concise test I could make.

The issue stems from trying to check if the ApolloClient in the context has the correct link URL, since this lib at the moment seems to store state in the `global.window`, the only way for me to make more than 1 test work is by resetting the content of the variables this library sets in `window`.

2 things I want to ask:

1. Why does this need to store the state in the `window`?
2. Can we export those symbols for type safety? redeclaring them myself as well as the type definition in the `window` interface is bound to be error prone.

![image](https://github.com/apollographql/apollo-client-nextjs/assets/9698639/afc9b3b5-f939-4918-aa80-92c56e8fbd3d)

**Comment by luchillo17** [comment]
The specific file where I got the symbols from: [package/src/ssr/ApolloRehydrateSymbols.tsx](https://github.com/apollographql/apollo-client-nextjs/blob/main/package/src/ssr/ApolloRehydrateSymbols.tsx#L7-L14)

**Comment by phryneas** [comment]
Hi @luchillo17, good point, this needs some way to reset in tests.

I don't want to expose the symbols though - this is an implementation detail and can change in future versions. Instead, I've added a `resetNextSSRApolloSingletons` function in #35.

You can use it like

```ts
afterEach(resetNextSSRApolloSingletons);
```

As for your question

> Why does this need to store the state in the window?

These singletons are needed to transport data from SSR into the browser - as the Client in the browser already starts up before the SSR pass finishes, we need to continuously push data from the server into the browser client.  
Next.js actually does something very similar to this, take a look at `window.__next_f`.

**Comment by phryneas** [comment]
A `0.2.0` release with this will be available in a moment :)

**Comment by luchillo17** [comment]
Awesome, will try it ASAP.

**Comment by luchillo17** [comment]
Not working unfortunatelly, these are your resets:
```ts
    delete window[ApolloRehydrationCache];
    delete window[ApolloResultCache];
    delete window[ApolloSSRDataTransport];
```
And these are mine:
```ts
    delete window[ApolloResultCache];
    delete window[ApolloClientSingleton];
    delete window[SuspenseCacheSingleton];
```

**Comment by luchillo17** [comment]
@phryneas can we re-open this? the resets you put were not enough in my test...

**Comment by phryneas** [comment]
Hi @luchillo17 I'm sorry for the delay - I'll put out a fix for this in a bit.

**Comment by phryneas** [comment]
Released with https://github.com/apollographql/apollo-client-nextjs/releases/tag/v0.2.2 - if there's anything else, please reopen, or create a new issue :)

**Comment by luchillo17** [comment]
Working perfectly, thanks.
