### ISSUE TITLE
Question about Queries when using SSR in client components

### ISSUE THREAD

**Issue by anthonyhoegberg** [apollographql/apollo-client-nextjs#349]
So i have a question when using NextJS client side components with apollo client SSR mode and where the queries are stored.

in this blog post: https://www.apollographql.com/blog/how-to-use-apollo-client-with-next-js-13

we have this following code snippet at the bottom
```ts
"use client";

import { useSuspenseQuery } from "@apollo/experimental-nextjs-app-support/ssr";

import { gql } from "@apollo/client";

const query = gql`query Now {
    now(id: "1")
}`;

export default function Page() {
  const { data } = useSuspenseQuery(query);

  return <main>{data.now}</main>;
}
```

So my question when we execute a query in the client side component, is the graphql query sent to the server then executed on the server and result sent back to the client component, or is the query stored server side and executed server side and results only sent to the client side? (basically writing a server side code but in client components)

If the query is stored on the client and sent to the server and executed as is, i feel like there could be some security problems if an user changes the query on the client side before executing it on the server using the SSR since even if the query is executed on the server it might not be what the original developer intended if modified by a third party

**Comment by phryneas** [comment]
Despite their name, in Next.js Client Components execute on the server for the first page load. 
These is nothing transported from client to server. Your component executes on the server, and we transport the result over so you don't make the same network request a second time.

**Comment by anthonyhoegberg** [comment]
Okay i see, so even if it looks like we are writing it on the client etc, its actually all executed on the server even if the graphql query itself is in a client component so the client never knows about the query itself or can change manipulate it in any way. Only the query result are transported to the client

Thanks for your clarification it really helped me decide on how to structure my project security wise in the simplest way possible
