### ISSUE TITLE
setting query headers fails on server

### ISSUE THREAD

**Issue by atarek12** [apollographql/apollo-client-nextjs#352]
I am trying to set some headers on the query inside RSC, I have tried two methods but with no luck.

- I have tried setting the locale header while firing the query itself 
```ts
  const { data } = await query(
    {
      query: Document,
      variables: { id },
      context: { headers: { locale } },
    }
  );
```

- I have also tried to set a common headers link 
```ts
import { registerApolloClient, ApolloClient } from "@apollo/experimental-nextjs-app-support";
import { ApolloLink, from } from "@apollo/client";
import { cookies } from "next/headers";

const localeLink = new ApolloLink((operation, forward) => {
  operation.setContext(({ headers = {} }) => ({
    headers: {
      ...headers,
      locale: cookies().get(CookieEnum.LANG)?.value,
    },
  }));

  return forward(operation);
});

const link = from([localeLink, httpLink]);

export const { getClient, query, PreloadQuery } = registerApolloClient(() => {
  return new ApolloClient({
    cache,
    link,
  });
});
```

What I expect is to set the locale headers properly

**Comment by phryneas** [comment]
Both of these should work - are you sure that `cookies().get(CookieEnum.LANG)?.value` returns something? Could you log that?

Also, generally I'd recommend to move the links into `registerApolloClient`, and you **have** to do the `new InMemoryCache` call inside of `registerApolloClient`, or you will leak potentially sensitive data between users.
