### ISSUE TITLE
useSuspenseQuery: Server functions cannot be called on initial render.

### ISSUE THREAD

**Issue by chris-snow** [apollographql/apollo-client-nextjs#355]
I've swapped out useQuery for useSuspenseQuery and I'm now getting the following error:

`ApolloError: Server Functions cannot be called during initial render. This would create a fetch waterfall. Try to use a Server Component to pass data to Client Components instead.`

This is happening (assumption noted) because I am calling a server function to retrieve my authorization token when creating my authLink for the client side apollo client:

```
const authLink = setContext(async (_, { headers }) => {
    const token = await getAuthToken(); <-- Server function

    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : "",
      },
    };
  });
  ```
  
 This error does not get shown when using useQuery, only when using useSuspenseQuery. I've attempted other methods of retrieving my token but unfortunately cannot reliably do this.
 
 1. Created a route handler to retrieve the token. This works for the client side, but fails on the initial server request due to the path not being absolute. I know I can work around this, but would prefer not to if possible.
 2. I'm unable to use 3rd party cookie libraries to read the token on the client side as it is httpOnly (which I'd prefer to keep as is for obvious reasons).
 3. I could pass the token in as a prop from the ApolloWrapper, but unfortunately I have no way to reliably ensure that the token is regularly updated (i.e. read once on mount, it will become stale after a period of time).
 
 I use PreloadQuery (as covered in the docs):
 
 Parent component:
 ```
 <PreloadQuery
        query={QueryDocumentDocument}
        variables={{
          take: 10,
          skip: 0,
        }}
      >
        <Suspense fallback={<ChildComponentLoading />}>
          <ChildComponent />
        </Suspense>
      </PreloadQuery>
 ```
 
 Child component:
```
const { data } = useSuspenseQuery<Query, QueryVariables>(
    QueryDocument,
    {
      variables: {
        filter: {
          take: pageSize,
          skip: (currentPage - 1) * pageSize,
        },
      },
    },
  );

```

Any assistance would be greatly appreciated.

**Comment by chris-snow** [comment]
Thanks for your response. The path I've decided to take, based on your suggestion, is altering my API so that it can accept either cookie or header based authentication.

The RSC client sends the header based auth, and the 'client' client sends credential based cookies. NextJS not making things easy but at least I have a workaround for the timebeing.

I still seem to be getting an unauthorized response on my very first RSC request, but I'll just have to live with that - I'm no longer getting the error I mentioned above.

Appreciate your help!

**Comment by withintheruins14** [comment]
> is there a approach to solve it ??

i think it's possible, the rest of my app does this but now I am suddenly getting an error for one page, stay posted

**Comment by withintheruins14** [comment]
you just need to await the prefetchedQuery in the Page, that clears the client error @ikaasraa

**Comment by withintheruins14** [comment]
> > you just need to await the prefetchedQuery in the Page, that clears the client error @ikaasraa
> 
> Please send some example

In the SRC (Page)
```
  const bobPromise = queryClient.prefetchQuery({
    queryKey: bobQueryKey,
    queryFn: () => getBob(accessToken),
  } as any);

  const promises = [bobPromise];
  
  await Promise.all(promises);
```

In the Client
```
  const { data: bobData } = useSuspenseQuery({
    queryKey: bobQueryKey,
    queryFn: () => getBob(accessToken as any),
  });
```

Boom, no error @ikaasraa

**Comment by jerelmiller** [comment]
@withintheruins14 that looks like TanStack Query code, not Apollo Client code. Are you sure you're in the right place?

**Comment by withintheruins14** [comment]
> @withintheruins14 that looks like TanStack Query code, not Apollo Client code. Are you sure you're in the right place?

you're right! I was just realzing this in the tub - anyhow I was making my rounds answering this question for people who might be stuck...! Deleting my response
