### ISSUE TITLE
'ApolloNextAppProvider' is not exported from '@apollo/experimental-nextjs-app-support' (imported as 'ApolloNextAppProvider').

### ISSUE THREAD

**Issue by lalithasj** [apollographql/apollo-client-nextjs#359]
Hi,

My apollo-client file:

```ts
import {  ApolloClient, InMemoryCache } from "@apollo/experimental-nextjs-app-support";
import { HttpLink } from "@apollo/client";

export default function makeClient() {
    const httpLink = new HttpLink({ 
        uri: 'http://localhost:3000/api/graphql',
        fetchOptions: { cache: 'no-store'}
    })
    return new ApolloClient({
        link: httpLink,
        cache: new InMemoryCache()
    })

}
```

My Layout file:

```tsx
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloNextAppProvider } from "@apollo/experimental-nextjs-app-support";
import makeClient from "@/lib/apollo-client";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloNextAppProvider makeClient={makeClient}>
        {children}
        </ApolloNextAppProvider>
        </body>
    </html>
  );
}
```

Error:

Import trace for requested module:
```
./src/app/layout.js
 ⚠ ./src/app/layout.js
Attempted import error: 'ApolloNextAppProvider' is not exported from '@apollo/experimental-nextjs-app-support' (imported as 'ApolloNextAppProvider').
```

Appreciate any suggestions or help

Thanks

**Comment by jerelmiller** [comment]
Hey @lalithasj 👋 

Are you using the `"use client"` pragma in either your client file or layout file? `ApolloNextAppProvider` is only available in Client Components so its possible that Next.js thinks you're trying to build these as Server Components where `ApolloNextAppProvider` is not available.

**Comment by lalithasj** [comment]
Hi @jerelmiller,  
Thank you for your response. ApolloNextAppProvider in my layout file (app router) and there is no 'use client' statement above that file. Appreciate any help

**Comment by jerelmiller** [comment]
You'll need to add `"use client"` in order for this to work. That will enable this as a client component and will make that import available. Try that out and see if that helps.

**Comment by lalithasj** [comment]
Hi @jerelmiller ,
Thanks for your suggestion. Now it's working by adding 'use client' and removing metadata.

**Comment by jerelmiller** [comment]
Great to hear!
