### ISSUE TITLE
How to synchronize cache of server components to the client?

### ISSUE THREAD

**Issue by i-tengfei** [apollographql/apollo-client-nextjs#37]
server component

```
const client = getClient()
client.query({
   ...
})
```

And then, when I checked the cache in the browser, the result did not get synchronized, which may cause the cache to not get updated after using useMutation.

**Comment by i-tengfei** [comment]
I found the answer, [When should you use Client Components vs Server Components?](https://www.apollographql.com/blog/announcement/frontend/using-apollo-client-with-next-js-13-releasing-an-official-library-to-support-the-app-router/#when-should-you-use-client-components-vs-server-components)

**Comment by phryneas** [comment]
On top of that, I'm gonna quote the [README for this package](https://github.com/apollographql/apollo-client-nextjs#usage) as a TLDR of that article:

> ❗️ We do handle "RSC" and "SSR" use cases as completely separate.
You should generally try not to have overlapping queries between the two, as all queries made in SSR can dynamically update in the browser as the cache updates (e.g. from a mutation or another query), but queries made in RSC will not be updated in the browser - for that purpose, the full page would need to rerender. As a result, any overlapping data would result in inconsistencies in your UI.
So decide for yourself, which queries you want to make in RSC and which in SSR, and don't have them overlap.
