### ISSUE TITLE
Best Approach for Prefetching Multiple Queries in Apollo with Next.js?

### ISSUE THREAD

**Issue by naimulemon** [apollographql/apollo-client-nextjs#371]
I’m working with Apollo Client in a Next.js 14 project and trying to prefetch multiple GraphQL queries using PreloadQuery. I want to ensure that this is the correct approach for prefetching multiple queries and handling the data efficiently within the component.

```
const IndexPage: React.FC = () => {
  return (
    <>
      <ApolloWrapper>
        <PreloadQuery query={ProductDocument}>
          <PreloadQuery
            query={gql(`query ProductDiscount($productId: Int!) {
  productDiscount(productId: $productId) {
    id
    discount
    offerTitle
  }
}`)}
          >
            <Suspense fallback={<div>Loading...</div>}>
              <ProductComponent />
            </Suspense>
          </PreloadQuery>
        </PreloadQuery>
      </ApolloWrapper>
    </>
  );
};

```

Is this a recommended way to prefetch multiple queries using PreloadQuery?
Are there more efficient or cleaner alternatives for handling multiple queries in this scenario, particularly with regards to code readability and performance?

**Comment by phryneas** [comment]
The general advice would be to use [fragment colocation](https://www.apollographql.com/docs/react/data/fragments#colocating-fragments) to compose all your data needs into one query, but if you are using more than one query per router, you're already doing it right.
