### ISSUE TITLE
Error handling with PreloadQuery

### ISSUE THREAD

**Issue by MiroYar** [apollographql/apollo-client-nextjs#393]
Hello. Tell me how to correctly handle query error a type of `GraphQLFormattedError`. I preload user data using `PreloadQuery`, the correctness of the request depends on cookies, but if for some reason the cookies turn out to be incorrect, the error `401 Forbidden` is returned. When I received this error, I wanted to redirect to the authorization page. I've tried several ways:
1. I did not find any corresponding props in the `PreloadQuery` component, except for the `errorPolicy="all"` parameter, but then `useSuspenseQuery` tries to make a repeat request, which I would like to avoid;
2. If redirect is used in the onError function in the client settings, then Next itself returns the error `Error: NEXT_REDIRECT`.

**Comment by phryneas** [comment]
As that query finishes after your page has already partially rendered, it's probably not possible to do this on the server during RSC or SSR.

Your only chance is to do this in the browser, and if a server query failed, the browser will always try to restart it there - the error itself is currently not transported over (that will change once we finish #389), so the browser has to restart.

**Comment by MiroYar** [comment]
Thanks for the reply. I understood you. The only thing I would like to know is how you estimate how long you will do the work [#389](https://github.com/apollographql/apollo-client-nextjs/pull/389), so that I will set a reminder to return to this problem.

**Comment by phryneas** [comment]
It's very high on my list of priorities, but even more important things keep popping up. 
Any other time of the year I'd say "a month", but with Thanksgiving and Christmas it could also take two.

**Comment by MiroYar** [comment]
Thank you very much.
