### ISSUE TITLE
Am I correct in understanding that PreloadQuery is fetching in RSC and passing the cache to the client?

### ISSUE THREAD

**Issue by YukiOnishi1129** [apollographql/apollo-client-nextjs#397]
Hello! 

I have a question about the behavior of PreloadQuery.

I read here that PreloadQuery uses RSC to fetch data to the API server and passes the cache to the client component.

https://github.com/apollographql/apollo-client-nextjs?tab=readme-ov-file#preloading-data-in-rsc-for-usage-in-client-components

I am aware that the useSuspenseQuery performed by the client component only goes to take a cache and does not work with the server, is that correct?

**Comment by phryneas** [comment]
Yes, `PreloadQuery` will make a network request on the server and then replay that in your client components, as if that request would have happened in your SSR pass or in the browser.

> I am aware that the useSuspenseQuery performed by the client component only goes to take a cache and does not work with the server, is that correct?

`useSuspenseQuery` can only be used in the client components and as such only have a single SSR pass on first page load, unlike RSC, which will run on the server on each navigation.

**Comment by YukiOnishi1129** [comment]
Thanks!

I am relieved to hear that!
