### ISSUE TITLE
Working with SSG?

### ISSUE THREAD

**Issue by DevelonPro** [apollographql/apollo-client-nextjs#41]
Hi,

I have managed to successfully setup this with SSR (`useSuspenseQuery()`) and works as expected. However, when I tried to statically generate the pages for faster loading times, when switching between pages client side it still fires off the GraphQL requests before changing to the next page. If I look at the generated page files, I can see that the JSON for the cache is included in the page but yet it must not be filling the cache client-side.

Is SSG achievable with this library or will I have to stick with SSR for now?

**Comment by phryneas** [comment]
This will work once we finished up https://github.com/apollographql/apollo-client-nextjs/pull/38, but so far `useSuspenseQuery` is not supported yet.

**Comment by phryneas** [comment]
@alessbell just published 0.3.0 which now supports this :)
https://github.com/apollographql/apollo-client-nextjs/releases/tag/v0.3.0
