### ISSUE TITLE
Client component error with the last package version

### ISSUE THREAD

**Issue by leidsoncruz** [apollographql/apollo-client-nextjs#54]
## Description

Following this [guide](https://www.apollographql.com/blog/apollo-client/next-js/how-to-use-apollo-client-with-next-js-13/) to use the Apollo client into the client component I'm receiving this error: `TypeError: useFn is not a function`.

I'm using the last version of both packages: `@apollo/client": "^3.8.0-alpha.15"` and `@apollo/experimental-nextjs-app-support": "^0.3.2"`.  Using the previous versions: `@apollo/client": "3.8.0-alpha.13"` and `@apollo/experimental-nextjs-app-support": "^0.1.0"`, it works perfectly. 

<details>
<summary>screenshots</summary>
<img width="955" alt="Screenshot 2023-07-05 at 18 30 23" src="https://github.com/apollographql/apollo-client-nextjs/assets/1443102/d1538412-ad4e-40bf-a358-48e8140509e6">

![Screenshot 2023-07-05 at 18 30 30](https://github.com/apollographql/apollo-client-nextjs/assets/1443102/04f834d3-dcda-474f-b0dc-41914b0999af)

</details>

## Code

<details>
<summary>Provider</summary>

```
//apollo provider

'use client';

import {
  ApolloClient,
  ApolloLink,
  HttpLink,
  SuspenseCache,
} from '@apollo/client';
import {
  ApolloNextAppProvider,
  NextSSRInMemoryCache,
  SSRMultipartLink,
} from '@apollo/experimental-nextjs-app-support/ssr';
import React from 'react';

function makeClient() {
  const httpLink = new HttpLink({
    uri: 'https://main--time-pav6zq.apollographos.net/graphql',
  });

  return new ApolloClient({
    cache: new NextSSRInMemoryCache(),
    link:
      typeof window === 'undefined'
        ? ApolloLink.from([
            new SSRMultipartLink({
              stripDefer: true,
            }),
            httpLink,
          ])
        : httpLink,
  });
}

function makeSuspenseCache() {
  return new SuspenseCache();
}

export function ApolloWrapper({ children }: React.PropsWithChildren) {
  return (
    <ApolloNextAppProvider
      makeClient={makeClient}
      makeSuspenseCache={makeSuspenseCache}
    >
      {children}
    </ApolloNextAppProvider>
  );
}
```
</details>

<details>
<summary>layout</summary>

```
import { ApolloWrapper } from 'shared';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
```
</details>

<details>
<summary>page</summary>

```
'use client';

import { gql } from '@apollo/client';
import { useSuspenseQuery } from '@apollo/experimental-nextjs-app-support/ssr';

const query = gql`
  query Now {
    now(id: "1")
  }
`;

export default function Page() {
  const { data } = useSuspenseQuery(query);
  return <main>{data.now}</main>;
}

```
</details>

**Comment by jerelmiller** [comment]
Hey @leidsoncruz 👋 

Can you try the _beta_ release of `@apollo/client` instead (`npm install @apollo/client@beta`)? [v0.2.0](https://github.com/apollographql/apollo-client-nextjs/releases/tag/v0.2.0) switched to support the beta releases which uses a different import of `useSuspenseQuery`. See if this helps!

**Comment by leidsoncruz** [comment]
> Hey @leidsoncruz 👋
> 
> Can you try the _beta_ release of `@apollo/client` instead (`npm install @apollo/client@beta`)? [v0.2.0](https://github.com/apollographql/apollo-client-nextjs/releases/tag/v0.2.0) switched to support the beta releases which uses a different import of `useSuspenseQuery`. See if this helps!

Hey @jerelmiller , thanks for the answer. Yes, it's working now. However, the experimental nextjs app support still with error: 

```
- error ../../node_modules/@apollo/experimental-nextjs-app-support/dist/ssr/RehydrationContext.js (26:0) @ RehydrationContextProvider
- error Error: When using Next SSR, you must use the `NextSSRApolloClient`
```

You can check the screenshot in the issue.

**Comment by jerelmiller** [comment]
@leidsoncruz try switching this line:

```ts
return new ApolloClient({
```

to

```ts
return new NextSSRApolloClient({
```

You can see an example of this in the README: https://github.com/apollographql/apollo-client-nextjs#in-ssr

---

Out of curiosity, is the error not clear enough? Let us know if you have feedback here that could help improve this. Thanks.

**Comment by leidsoncruz** [comment]
Hey, @jerelmiller! It's working perfectly. Thanks. Sorry for the delay to reply.

> Out of curiosity, is the error not clear enough? Let us know if you have feedback here that could help improve this. Thanks.

Analysing the error and the solution, it's very clear. The problem was I tried a lot of things before without success and the [post](https://www.apollographql.com/blog/apollo-client/next-js/how-to-use-apollo-client-with-next-js-13/) on the official blog is using ApolloClient (probably they are using an older version).

**Comment by phryneas** [comment]
The blog article should be updated now. Thanks for pointing that out @leidsoncruz !
