### ISSUE TITLE
Support Next.js cache options on `fetch`

### ISSUE THREAD

**Issue by moshest** [apollographql/apollo-client-nextjs#72]
I follow the tutorial of [using Apollo with Next.js App directory](https://www.apollographql.com/blog/announcement/frontend/using-apollo-client-with-next-js-13-releasing-an-official-library-to-support-the-app-router/).

I notice the tutorial ask to add the `force-dynamic` parameter to the page to control if Next.js should cache the response. Although this solution works I find it very hard to maintain, especially if I have child components that require dynamic rendering.

Next.js solve that by providing `cache: 'no-store'` on the `fetch` function ([docs](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating)) so the engine will know which request shouldn't be cached.

I currently solve it for my use case by setting it to `no-store` for all GraphQL requests:

```ts
export const link = new HttpLink({
  uri: `https://example.com/graphql`,
  fetchOptions: {
    cache: 'no-store',
  },
});
```

Is there an option to control the `fetch` option using the `fetchPolicy` on `useSuspenseQuery`?

I expect `useSuspenseQuery` to send `no-store` for every request UNLESS I choose to cache it on build time. Something like the following will be ideal:

```ts
// default behavior
const { data } = useSuspenseQuery(MY_QUERY, {
  // fetchCache: 'no-store',
});

// override default
const { data } = useSuspenseQuery(MY_QUERY, {
  fetchCache: 'force-cache',
});
```

**Comment by phryneas** [comment]
That said, that's pretty much baked in already with what you have.

```js
export const link = new HttpLink({
  uri: `https://example.com/graphql`,
  fetchOptions: {
    cache: 'no-store',
  },
});
```

sets that default, and you can overwrite it with
```js
// override default
const { data } = useSuspenseQuery(MY_QUERY, {
  context: { fetchOptions: { fetchCache: "force-cache" }},
});
```

**Comment by moshest** [comment]
You are right, I manage to config it as following:

```ts
// set default cache options for all requests
const link = new HttpLink({
  uri: `https://example.com/graphql`,
  fetchOptions: {
    cache: 'no-store',
  },
});

// override default
const { data } = useSuspenseQuery(MY_QUERY, {
  context: { fetchOptions: { cache: "force-cache" }},
});
```

I think this should be the recommend behavior for all users. It's much better DX then setting `force-dymanic` on each page. Maybe we can update the [docs](https://github.com/apollographql/apollo-client-nextjs/blob/main/package/README.md) to match?

**Comment by phryneas** [comment]
@moshest what do you think about #73 ?

**Comment by moshest** [comment]
Amazing!
