### ISSUE TITLE
Update README file since this package is not expernemtal anymore 

### ISSUE THREAD

**Issue by ariannargesi** [apollographql/apollo-client-nextjs#77]
Thanks for this package 
Would be great if you can update the README file. I think it's a bit old. 
Also please update the name of the package on npm.
If there is anything that I can do to help you in the process, Please let me know. 
Happy to help

**Comment by jerelmiller** [comment]
Hey @ariannargesi 👋 

For now we plan to keep the "experimental" as part of the name until we are 100% confident we've got the right implementation in place. There have been [subtle breakages](https://github.com/apollographql/apollo-client/issues/10974) in Next.js versions that have gotten are attention and help us to consider if we are approaching this the right way.

I promise this won't be experimental forever and ideally we'll get a new [React primitive](https://github.com/brillout/rfcs/blob/main/text/0000-inject-to-stream.md) at some point that would eliminate the need for a lot of what this package does behind the scenes.

For now, I'm going to close this issue. We'll be continuously evaluating the right time to make this a non-experimental package. Thanks for raising the question!
