### ISSUE TITLE
How to merge cache with NextSSRInMemoryCache

### ISSUE THREAD

**Issue by VahanDrnoyan** [apollographql/apollo-client-nextjs#82]
Hello,

Could you mention how to merge the initial cache with newly received data with NextSSRInMemoryCache.

For example, I have pagination, and a want the data fetched from clicking on page one to be preserved in the cache, and once I come back from page 2, it should not be fetched with the new request but served from the Apollo client cache. This was possible in NextJs 12.

Thank you in advance.

**Comment by plausible-phry** [comment]
Can you explain a little more what puzzle piece is missing here/what you were doing before and what is not working for you now?

`NextSSRInMemoryCache` just extends the normal `InMemoryCache` - it has all the same functionalities you are already used to and just adds streaming synchronization in the browser for SSRed pages on top.

**Comment by VahanDrnoyan** [comment]
Hello, @plausible-phry 

Thank you for your answer, this is what I mean. This is the code I used with Apollo and NextJs 12.

In my main _app.ts
`
function MyApp({Component, pageProps: {session, ...pageProps}}: CustomAppProps) {
    const apolloClient = useApollo(**pageProps.initialApolloState**);
    return (
`

Before I was getting the initial Apollo state, which was passed from serverside to page component and was merging it with the newly created Apollo cache in the client side:


`
function createApolloClient() {
  return new ApolloClient({
    ssrMode: typeof window === "undefined",
    link: createIsomorphLink(),
    cache,
  })
}


export function useApollo(initialState: MyApolloCache) {
  const store = useMemo(() => **initializeApollo(initialState), [initialState]);**
  return store;
}

export function initializeApollo(initialState: MyApolloCache | null = null) {
  const _apolloClient = apolloClient ?? createApolloClient();

  if (initialState) {
    const existingCache = _apolloClient.extract();
    **_apolloClient.cache.restore({ ...existingCache, ...initialState });**
  }
  if (typeof window === 'undefined') return _apolloClient;
  if (!apolloClient) apolloClient = _apolloClient;

  return _apolloClient;
}

export function useApollo(initialState: MyApolloCache) {
  const store = useMemo(() => initializeApollo(initialState), [initialState]);
  return store;
}
`
How this type of setup might be translated to the new Next JS 13?

Thank you in advance.

**Comment by plausible-phry** [comment]
You can't do a "one time rehydration" anymore since with Next.js, your SSR can still be running while  browser already renders and is interactive.

Instead, we transport every query over bit by bit. That happens under the hood, and you don't need to do anything regarding hydration - just use the hooks exported by this package.

That said, though, we can only do that for the suspenseful hooks `useSuspenseQuery` and `useBackgroundQuery` - the old `useQuery` hook will not do any data fetching on the server, but only start working in the browser.

**Comment by VahanDrnoyan** [comment]
However can I use caching policies like these? 

![image](https://github.com/apollographql/apollo-client-nextjs/assets/23120503/df74a945-3c57-4a60-9804-1227f8db3353)

**Comment by plausible-phry** [comment]
That doesn't really have anything to do with rehydration, so I don't see why you could not?

**Comment by VahanDrnoyan** [comment]
Thank you!
