### ISSUE TITLE
how the logs are configured for the polls-demo example?

### ISSUE THREAD

**Issue by immanu10** [apollographql/apollo-client-nextjs#86]
<img width="907" alt="Screenshot 2023-08-21 at 6 03 25 PM" src="https://github.com/apollographql/apollo-client-nextjs/assets/54578417/8c423904-9a7d-410b-a79a-8d5fcb244325">

I'm unable to find out from where exactly these GET, POST log messages are coming from. I want to have it in my nextjs project as well. Please help.

**Comment by plausible-phry** [comment]
I wish I could tell you more, but I didn't do anything specific to get those - they were just there.

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.
