### ISSUE TITLE
How to use useMutation with apollo/experimental-nextjs-app-support?

### ISSUE THREAD

**Issue by luc345** [apollographql/apollo-client-nextjs#87]
I am trying out apollo/experimental-nextjs-app-support and followed the documentation to add an app/ApolloWrapper.jsx.
However, I am unable to successfully use useMutation. 
Is this package specifically for queries only, or am I doing something wrong? 

I am using Next.js version 13.4.12. 
Thank you for your help.

**Comment by phryneas** [comment]
You can just use the regular `useMutation` hook from `@apollo/client`. Since mutations will never happen as part of a component render, they need no special treatment for the NextJs app directory.

**Comment by luc345** [comment]
Okay, much appreciated
