### ISSUE TITLE
useSuspenseQuery not working right with variables

### ISSUE THREAD

**Issue by kolyabazlov** [apollographql/apollo-client-nextjs#89]
I have an issue when passing any variable to useSuspenseQuery is not using variables and returns empty data.
I use codegen to generate queries and types.

Here is the pseudocode example:

client page example usage
```jsx
'use-client'

import { useSuspenseQuery } from '@apollo/experimental-nextjs-app-support/ssr';
import {
  TestQuery,
  TestQueryDocument,
} from 'generated/graphql';

export const dynamic = 'force-dynamic';

export default function Page() {
  const { data } = useSuspenseQuery<TestQuery>(TestQueryDocument, {
    variables: {
      numKey: '2468'
    }
  });
}
```

example query
```

query Test($numKey: String, $alphaKey: String) {
  results(filters: { or: [{ NumKey: { eq: $numKey } }, { AlphaKey: { eq: $alphaKey } }] }) {
    data {
      id
    } 
  }
}
```

server page example usage
```
  const { data } = await client.query<TestQuery>({
    query: TestQueryDocument,
    variables: {
      numKey: '2468'
    }
  });
```

#### Main points: 
- Returned data, that should be filtered by useSuspenseQuery variables is empty. 
- Without variables returns all data as should.
- If use same query with variables in server component everything works well.

**Comment by phryneas** [comment]
Completely unrelated, but maybe useful: you can skip that manual type annotation, it should pick up the types automatically (that is actually more typesafe!):
```diff
const { data } = useSuspenseQuery<TestQuery>(TestQueryDocument, {
const { data } = useSuspenseQuery(TestQueryDocument, {
```

---

For the problem at hand: I have never seen that happen before. Could you please create a minimal reproduction that I could take a look at - or make a [Replay](https://www.replay.io/) recording of what's going on in the browser?

**Comment by kolyabazlov** [comment]
@phryneas 

Hello, I have recreated my queries in the codesandbox and now I don't see any problem with using variables. Sorry, the reason must somewhere else.
