### ISSUE TITLE
refetchQueries not updating the cache post-mutation

### ISSUE THREAD

**Issue by guillaumetran** [apollographql/apollo-client-nextjs#92]
I am facing an issue with `refetchQueries` post-mutation after upgrading to Next 13. I have a list of episodes and I want to create a new episode elsewhere in my app. 
Before Next 13, I used `refetchQueries`, and it was quite straightforward. However, post-upgrade, even though the `refetchQuery` is happening in the Network (as observed), the cache in **Component 1** is not updated. I need to manually reload the page to visualize the updated data.

While I can update the cache directly using the `update` property in `useMutation`, in some scenarios, I prefer using `refetchQueries`.

It's possible that I might have missed some nuances with the recent changes in Next.js or perhaps there's a genuine concern here.

**Component 1 (displaying all episodes):**
```
"use client";
import { useQuery } from "@apollo/experimental-nextjs-app-support/ssr";

export function SerieEpisodes({ serieId }: { serieId: string }) {
  const { data, loading, error } = useQuery<SerieEpisodesQuery>(
    SerieEpisodesDocument,
    {
      variables: {
        id: serieId as string,
      },
    }
  );
```

**Component 2 (adding a new episode):**
```
"use client";
import { useMutation } from "@apollo/client";

export const AddEpisodeForm = ({ season }: { season: Season }) => {
const [createEpisode, { loading }] = useMutation(CreateEpisodeDocument, {
    refetchQueries: [
      {
        query: SerieEpisodesDocument,
        variables: { id: season?.serie?.id as string },
      },
    ],
    // Workaround to update cache instead of refetchQueries
    // update: (cache, { data }) => {
    //   cache.modify({
    //     id: cache.identify(season),
    //     fields: {
    //       episodes(existingEpisodes = []) {
    //         const newEpisodeRef = cache.writeQuery({
    //           data: data?.createEpisode,
    //           query: SerieEpisodesDocument,
    //           variables: { id: season?.serie?.id as string },
    //         });
    //         return [...existingEpisodes, newEpisodeRef];
    //       },
    //     },
    //   });
    // },
  });
```

Everything is wrapped as per the documentation:
```
export function ApolloWrapper({ children }: React.PropsWithChildren) {
  return (
    <ApolloNextAppProvider makeClient={makeClient}>
      {children}
    </ApolloNextAppProvider>
  );
}
```

Would appreciate insights or any pointers to resolve this. Thank you!

**Comment by phryneas** [comment]
I don't see anything in `@apollo/experimental-nextjs-app-support` that should influence this. 🤔 

Could you swap out the `useQuery` for `@apollo/client` only in this component and report if that changes the behaviour or not, just to make sure we're not looking at the wrong thing?

**Comment by guillaumetran** [comment]
I made a mistake in my code.. Everything is working fine. Sorry for taking your time. Closing the issue
