### ISSUE TITLE
useSuspenseQuery first refetchQueries doesn't trigger

### ISSUE THREAD

**Issue by tombryden** [apollographql/apollo-client-nextjs#93]
Hello,

I have noticed that useSuspenseQuery is not refetching on the first call after a mutation calls it in refetchQueries.

[Here is a gif of what occurs with added delay from the api](https://gyazo.com/dda0b0efec1c50686fa5720359cc621a)

When changing to useQuery, all works as expected.

### Page
```
import AddTodo from "@/components/add-todo";
import TodoList from "@/components/todo-list";
import { Box, Typography } from "@mui/material";

export default function Home() {
  return (
    <Box
      component="main"
      display="flex"
      flexDirection="column"
      alignItems="center"
    >
      <Typography variant="h2" component="h1" mb={2}>
        My Todo List
      </Typography>

      <AddTodo />

      <TodoList />
    </Box>
  );
}
```

### TodoList
```
"use client";

import { graphql } from "@/gql";
import { useSuspenseQuery } from "@apollo/experimental-nextjs-app-support/ssr";
import Todo from "./todo";

const GET_ALL_TODOS_QUERY = graphql(`
  query getAllTodos {
    todos {
      id
      text
      done
    }
  }
`);

export default function TodoList() {
  const { data } = useSuspenseQuery(GET_ALL_TODOS_QUERY, {
    context: { fetchOptions: { cache: "no-cache" } },
  });

  return data.todos.map((todo) => <Todo key={todo.id} todoId={todo.id} />);
}
```
### AddTodo
```
"use client";

import { graphql } from "@/gql";
import { useMutation } from "@apollo/client";
import { LoadingButton } from "@mui/lab";
import { Box, TextField } from "@mui/material";
import { useState } from "react";
import { GetAllTodosDocument } from "@/gql/graphql";

const ADD_NEW_TODO_MUTATION = graphql(`
  mutation addNewTodo($text: String!, $done: Boolean!) {
    saveTodo(todo: { text: $text, done: $done }) {
      id
      text
      done
    }
  }
`);

export default function AddTodo() {
  const [text, setText] = useState("");

  const [addTodo, { loading }] = useMutation(ADD_NEW_TODO_MUTATION, {
    refetchQueries: [{ query: GetAllTodosDocument }],
    awaitRefetchQueries: true,
  });

  return (
    <Box display="flex" gap={1}>
      <TextField
        label="Todo"
        value={text}
        onChange={(e) => setText(e.target.value)}
        sx={{ width: "500px" }}
      />

      <LoadingButton
        onClick={() =>
          addTodo({
            variables: { text, done: false },
          })
        }
        loading={loading}
      >
        Add
      </LoadingButton>
    </Box>
  );
}
```

Thanks

**Comment by phryneas** [comment]
Can you please check if this also occurs with the `useSuspenseQuery` from `@apollo/client`, so that we can pinpoint which of the two libraries we have to debug here? :)

**Comment by tombryden** [comment]
I gave this a quick try, however I am unfamiliar with next below 13 so I can't replicate this using the pages directory.

Using the app directly, `useSuspenseQuery` initially throws an (expected) error: Hydration failed because the initial UI does not match what was rendered on the server.

However once cached, no error is thrown so I think this test is viable. Refetchqueries works as expected in this case.

**Comment by tombryden** [comment]
I just retested using a toggle show button to avoid hydration issues.

Refetchqueries works as expected in this case.

**Comment by tombryden** [comment]
Arrr, I just retested the same scenario (toggle button) using the import from `@apollo/experimental-nextjs-app-support/ssr` and this refetches the first time successfully.

It looks like the issue only occurs when loading via SSR.

**Comment by tombryden** [comment]
Yes, I am on 0.4.2.

**Comment by phryneas** [comment]
I'll try to look into that next week. If you can provide me with a minimal reproduction, I would be very grateful!

**Comment by tombryden** [comment]
Thanks! Here you go: https://github.com/tombryden/experimental-apollo-suspense-bug

**Comment by phryneas** [comment]
Could you please verify if this build from #96 solves your problem?
```sh
npm i @apollo/experimental-nextjs-app-support@0.0.0-commit-6211d17
```

**Comment by phryneas** [comment]
This should be fixed with https://github.com/apollographql/apollo-client-nextjs/releases/tag/v.0.4.3

**Comment by tombryden** [comment]
Apologies for the delay! Can confirm this is now working as expected. Many thanks.
